### ISSUE TITLE
ANSHHHHHHHHHHHHHHH

### ISSUE THREAD

**Issue by krolyxon** [Anshieee/stuff#1]
remember me?

**Comment by Anshieee** [comment]
who is glizz?????

**Comment by Anshieee** [comment]
idk who glizz is

**Comment by krolyxon** [comment]
YOU FUCKING MoRon, BRO contact me pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeee krolyxon:matrix.org i fucking miss you so much

**Comment by krolyxon** [comment]
maaaaaaaaaaaaaaaaaaaaaaan?

**Comment by Anshieee** [comment]
wqit wsit i dont have a phone or a laptop rn. let me open element
